include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml  
  - template: Security/SAST.gitlab-ci.yml
  - project: eclipse/xfsc/dev-ops/ci-templates
    file: maven-standard-ci.yaml
    ref: main
    
variables:
  MAVEN_IMAGE: "maven:3.9-eclipse-temurin-17"
      
stages:
  - test
  - build
  - deploy
  
maven:test:
  script:
    - mvn $MAVEN_CLI_OPTS verify
    - cat fc-service-server/target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>'
  artifacts:
    paths:
      - 'fc-service-server/target/site/jacoco/index.html'

sast:
  stage: build
