apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
#    cert-manager.io/cluster-issuer: cert-manager-webhook
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
  name: fc-key-server-ingress
  namespace: federated-catalogue
spec:
  rules:
  - host: fc-key-server.gxfs.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fc-key-server-service
            port:
              number: 8080
  tls:
  - hosts:
    - fc-key-server.gxfs.dev
    secretName: wildcard-gxfs-dev
